/* Quiz Ladder question bank. d = difficulty 1 (base) to 5 (summit). i = correct index. */
const QUESTIONS = [
  { d:1, c:"World", q:"What is the capital of Canada?", a:["Toronto","Ottawa","Vancouver","Montreal"], i:1 },
  { d:1, c:"Science", q:"Water boils at what temperature at sea level?", a:["90°C","100°C","110°C","80°C"], i:1 },
  { d:1, c:"History", q:"In which year did Nigeria gain independence?", a:["1957","1960","1963","1970"], i:1 },
  { d:1, c:"Geography", q:"Which river is the longest in Africa?", a:["Congo","Niger","Nile","Zambezi"], i:2 },
  { d:1, c:"Science", q:"What gas do plants mainly absorb for photosynthesis?", a:["Oxygen","Nitrogen","Carbon dioxide","Helium"], i:2 },
  { d:1, c:"World", q:"How many continents are there in the common seven-continent model?", a:["5","6","7","8"], i:2 },
  { d:1, c:"Sport", q:"How many players are on the field for one football (soccer) team?", a:["9","10","11","12"], i:2 },
  { d:1, c:"Language", q:"What is the plural of 'child'?", a:["Childs","Childes","Children","Childrens"], i:2 },
  { d:1, c:"History", q:"Who was the first president of the United States?", a:["Abraham Lincoln","Thomas Jefferson","George Washington","John Adams"], i:2 },
  { d:1, c:"Science", q:"Which planet is known as the Red Planet?", a:["Venus","Jupiter","Mars","Saturn"], i:2 },
  { d:1, c:"Geography", q:"Lagos is a major city in which country?", a:["Ghana","Nigeria","Kenya","Senegal"], i:1 },
  { d:1, c:"Math", q:"What is 12 × 12?", a:["124","132","144","156"], i:2 },
  { d:1, c:"World", q:"Which ocean is the largest?", a:["Atlantic","Indian","Arctic","Pacific"], i:3 },
  { d:1, c:"Art", q:"Who painted the Mona Lisa?", a:["Michelangelo","Raphael","Leonardo da Vinci","Donatello"], i:2 },
  { d:1, c:"Science", q:"Humans have how many permanent teeth in a full adult set?", a:["28","30","32","36"], i:2 },
  { d:1, c:"History", q:"The Great Wall is in which country?", a:["Japan","China","India","Mongolia"], i:1 },
  { d:1, c:"Geography", q:"Which desert is the largest hot desert in the world?", a:["Gobi","Kalahari","Sahara","Arabian"], i:2 },
  { d:1, c:"Sport", q:"How many rings are on the Olympic flag?", a:["4","5","6","7"], i:1 },
  { d:1, c:"World", q:"What currency is used in Japan?", a:["Won","Yuan","Yen","Baht"], i:2 },
  { d:1, c:"Science", q:"What is the chemical symbol for gold?", a:["Ag","Au","Gd","Go"], i:1 },

  { d:2, c:"History", q:"The Berlin Wall fell in which year?", a:["1987","1989","1991","1993"], i:1 },
  { d:2, c:"Science", q:"What is the powerhouse of the cell?", a:["Nucleus","Ribosome","Mitochondrion","Golgi body"], i:2 },
  { d:2, c:"Geography", q:"Which country has the city of Timbuktu?", a:["Niger","Mali","Chad","Sudan"], i:1 },
  { d:2, c:"World", q:"Who wrote 'Things Fall Apart'?", a:["Wole Soyinka","Chinua Achebe","Ngũgĩ wa Thiong'o","Ben Okri"], i:1 },
  { d:2, c:"Science", q:"What is the hardest natural substance?", a:["Quartz","Corundum","Diamond","Topaz"], i:2 },
  { d:2, c:"History", q:"Who was the first woman to win a Nobel Prize?", a:["Marie Curie","Rosalind Franklin","Dorothy Hodgkin","Ada Lovelace"], i:0 },
  { d:2, c:"Math", q:"What is the square root of 256?", a:["14","15","16","18"], i:2 },
  { d:2, c:"Geography", q:"Mount Kilimanjaro is in which country?", a:["Kenya","Uganda","Tanzania","Ethiopia"], i:2 },
  { d:2, c:"Sport", q:"A marathon is officially how many kilometres, to the nearest tenth?", a:["40.2","41.2","42.2","43.2"], i:2 },
  { d:2, c:"World", q:"Which language has the most native speakers?", a:["English","Hindi","Spanish","Mandarin Chinese"], i:3 },
  { d:2, c:"Science", q:"What does DNA stand for?", a:["Deoxyribonucleic acid","Dinitrogen acid","Dual nucleic arrangement","Deoxyribose nitrate acid"], i:0 },
  { d:2, c:"History", q:"The ancient city of Carthage was in present-day which country?", a:["Libya","Tunisia","Algeria","Morocco"], i:1 },
  { d:2, c:"Geography", q:"Which African country is completely surrounded by South Africa?", a:["Eswatini","Lesotho","Botswana","Namibia"], i:1 },
  { d:2, c:"Art", q:"Beethoven's famous 5th symphony opens with how many notes in its motif?", a:["Three","Four","Five","Eight"], i:1 },
  { d:2, c:"Science", q:"Which blood type is the universal donor for red cells?", a:["AB+","O−","A−","B+"], i:1 },
  { d:2, c:"World", q:"The Nobel Peace Prize is awarded in which city?", a:["Stockholm","Oslo","Copenhagen","Helsinki"], i:1 },
  { d:2, c:"History", q:"Who led the Haitian Revolution to independence?", a:["Toussaint Louverture","Simon Bolivar","Kwame Nkrumah","Patrice Lumumba"], i:0 },
  { d:2, c:"Math", q:"A prime number has exactly how many positive divisors?", a:["One","Two","Three","It varies"], i:1 },
  { d:2, c:"Geography", q:"The Suez Canal connects the Mediterranean Sea to which sea?", a:["Black Sea","Red Sea","Arabian Sea","Caspian Sea"], i:1 },
  { d:2, c:"Science", q:"Light travels fastest in which of these?", a:["Water","Glass","Vacuum","Diamond"], i:2 },

  { d:3, c:"History", q:"The Mali Empire's famous ruler Mansa Musa made a legendary pilgrimage in which century?", a:["11th","13th","14th","16th"], i:2 },
  { d:3, c:"Science", q:"What is the approximate speed of light in vacuum?", a:["3,000 km/s","30,000 km/s","300,000 km/s","3,000,000 km/s"], i:2 },
  { d:3, c:"Geography", q:"Which strait separates Europe from Africa at the Mediterranean's west end?", a:["Bosphorus","Gibraltar","Malacca","Hormuz"], i:1 },
  { d:3, c:"World", q:"Who wrote the play 'Death and the King's Horseman'?", a:["Wole Soyinka","Femi Osofisan","Ama Ata Aidoo","Buchi Emecheta"], i:0 },
  { d:3, c:"Science", q:"Which particle has a negative electric charge?", a:["Proton","Neutron","Electron","Photon"], i:2 },
  { d:3, c:"History", q:"The Treaty of Westphalia, often tied to the modern state system, was signed in which year?", a:["1517","1648","1789","1815"], i:1 },
  { d:3, c:"Math", q:"What is the value of pi rounded to three decimal places?", a:["3.141","3.142","3.144","3.147"], i:1 },
  { d:3, c:"Geography", q:"Lake Victoria is shared mainly by Uganda, Kenya, and which country?", a:["Rwanda","Tanzania","DR Congo","Ethiopia"], i:1 },
  { d:3, c:"Sport", q:"In chess, which piece can jump over other pieces?", a:["Bishop","Rook","Knight","Queen"], i:2 },
  { d:3, c:"Science", q:"The pH of pure water at 25°C is about what?", a:["5","6","7","8"], i:2 },
  { d:3, c:"History", q:"Who was the British prime minister at the start of World War II in 1939?", a:["Winston Churchill","Neville Chamberlain","Clement Attlee","Stanley Baldwin"], i:1 },
  { d:3, c:"World", q:"Which country uses the naira?", a:["Ghana","Nigeria","Kenya","Egypt"], i:1 },
  { d:3, c:"Science", q:"What organ produces insulin?", a:["Liver","Pancreas","Kidney","Spleen"], i:1 },
  { d:3, c:"Geography", q:"The Andes run primarily along which continent?", a:["Africa","Asia","South America","Europe"], i:2 },
  { d:3, c:"Art", q:"'The Persistence of Memory' is by which painter?", a:["Salvador Dalí","Pablo Picasso","René Magritte","Joan Miró"], i:0 },
  { d:3, c:"Math", q:"How many degrees are in a triangle's interior angles?", a:["90","180","270","360"], i:1 },
  { d:3, c:"History", q:"Apartheid formally ended as a legal system in South Africa in which decade?", a:["1970s","1980s","1990s","2000s"], i:2 },
  { d:3, c:"Science", q:"Which vitamin is produced in the skin when exposed to sunlight?", a:["Vitamin A","Vitamin C","Vitamin D","Vitamin K"], i:2 },
  { d:3, c:"World", q:"The African Union headquarters is in which city?", a:["Abuja","Nairobi","Addis Ababa","Accra"], i:2 },
  { d:3, c:"Geography", q:"Which country is both in Europe and Asia?", a:["Spain","Turkey","Poland","Egypt"], i:1 },

  { d:4, c:"Science", q:"Avogadro's number is approximately which of these?", a:["6.022 × 10^23","3.00 × 10^8","9.81","1.602 × 10^-19"], i:0 },
  { d:4, c:"History", q:"The Scramble for Africa was formalized in large part at the Berlin Conference of which years?", a:["1871–1872","1884–1885","1904–1905","1919–1920"], i:1 },
  { d:4, c:"Geography", q:"Which is the deepest ocean trench?", a:["Puerto Rico Trench","Java Trench","Mariana Trench","Tonga Trench"], i:2 },
  { d:4, c:"World", q:"Who wrote 'The Famished Road'?", a:["Ben Okri","Helon Habila","Chimamanda Ngozi Adichie","Teju Cole"], i:0 },
  { d:4, c:"Science", q:"Which law says that current is proportional to voltage for a given resistance?", a:["Newton's second","Ohm's law","Faraday's law","Boyle's law"], i:1 },
  { d:4, c:"History", q:"The Battle of Adwa, an Ethiopian victory over Italy, was fought in which year?", a:["1868","1896","1935","1941"], i:1 },
  { d:4, c:"Math", q:"The derivative of x² with respect to x is?", a:["x","2x","x³","2"], i:1 },
  { d:4, c:"Geography", q:"Which capital city is the highest by elevation among these?", a:["La Paz","Quito","Addis Ababa","Kathmandu"], i:0 },
  { d:4, c:"Science", q:"CRISPR is best known as a tool for what?", a:["Weather modeling","Gene editing","Satellite navigation","Battery chemistry"], i:1 },
  { d:4, c:"History", q:"Who was the first Secretary-General of the United Nations?", a:["Dag Hammarskjöld","Trygve Lie","U Thant","Kurt Waldheim"], i:1 },
  { d:4, c:"World", q:"The Booker Prize-winning 'Half of a Yellow Sun' is set mainly during which conflict?", a:["Biafran War","Rwandan genocide","Algerian War","Angolan Civil War"], i:0 },
  { d:4, c:"Science", q:"Which element has atomic number 26?", a:["Copper","Iron","Nickel","Zinc"], i:1 },
  { d:4, c:"Geography", q:"The Danube flows into which sea?", a:["Baltic","Adriatic","Black","Caspian"], i:2 },
  { d:4, c:"Art", q:"The harmonic series in music is most closely tied to which phenomenon?", a:["Beats only","Overtones of a vibrating string or air column","Equal temperament exclusively","Syncopation"], i:1 },
  { d:4, c:"History", q:"Constantinople fell to the Ottomans in which year?", a:["1204","1453","1492","1526"], i:1 },
  { d:4, c:"Science", q:"A black hole's boundary, beyond which light cannot escape, is called the?", a:["Event horizon","Photon sphere only","Singularity wall","Accretion lip"], i:0 },
  { d:4, c:"Math", q:"In base 2, what is 1011 equal to in decimal?", a:["9","10","11","13"], i:2 },
  { d:4, c:"World", q:"Which philosopher wrote 'Thus Spoke Zarathustra'?", a:["Kant","Nietzsche","Hegel","Schopenhauer"], i:1 },
  { d:4, c:"Geography", q:"Which country has the most time zones, including overseas territories, among these?", a:["Russia","France","United States","China"], i:1 },
  { d:4, c:"Science", q:"Photosystem II splits water to release which gas?", a:["Nitrogen","Carbon dioxide","Oxygen","Hydrogen sulfide"], i:2 },

  { d:5, c:"Science", q:"Planck's constant is on the order of which value?", a:["6.626 × 10^-34 J·s","6.626 × 10^-23 J·s","1.38 × 10^-23 J/K","9.109 × 10^-31 kg"], i:0 },
  { d:5, c:"History", q:"The Haitian Declaration of Independence was proclaimed in which year?", a:["1791","1804","1822","1848"], i:1 },
  { d:5, c:"Geography", q:"Which river's drainage basin is the largest in the world?", a:["Nile","Congo","Amazon","Mississippi"], i:2 },
  { d:5, c:"World", q:"In logic, 'modus ponens' allows you to infer what from 'If P then Q' and 'P'?", a:["Not P","Not Q","Q","P and not Q"], i:2 },
  { d:5, c:"Science", q:"The half-life of carbon-14 is closest to which figure?", a:["573 years","5,730 years","57,300 years","573,000 years"], i:1 },
  { d:5, c:"History", q:"Who was the Ashanti ruler who fought the British in the late 19th century and was exiled?", a:["Osei Tutu","Prempeh I","Shaka","Menelik II"], i:1 },
  { d:5, c:"Math", q:"Euler's identity famously links which set?", a:["e, i, π, 1, and 0","only π and e","primes and composites","triangles and circles only"], i:0 },
  { d:5, c:"Geography", q:"The Kalahari is chiefly a desert of which kind of rainfall regime?", a:["Ice cap","Semi-arid with summer rain in much of it","Equatorial rainforest","Mediterranean winter-only everywhere"], i:1 },
  { d:5, c:"Science", q:"Heisenberg's uncertainty principle limits simultaneous precision of which pair?", a:["Mass and charge","Position and momentum","Temperature and volume","Spin and color"], i:1 },
  { d:5, c:"History", q:"The Rosetta Stone was key because it carried the same text in Greek and which scripts?", a:["Latin and cuneiform","Demotic and hieroglyphic","Sanskrit and Pali","Arabic and Coptic only"], i:1 },
  { d:5, c:"World", q:"Gödel's incompleteness theorems concern which field?", a:["Optics","Formal arithmetic systems","Plate tectonics","Monetary policy"], i:1 },
  { d:5, c:"Science", q:"Which particle mediates the electromagnetic force?", a:["Gluon","W boson","Photon","Graviton"], i:2 },
  { d:5, c:"Geography", q:"The Wallace Line is a biogeographic boundary mainly between which regions?", a:["Africa and Europe","Asia and Australasia","North and South America","Antarctica and the Southern Ocean only"], i:1 },
  { d:5, c:"History", q:"The Congress of Vienna, reshaping Europe after Napoleon, began in which year?", a:["1789","1814","1848","1871"], i:1 },
  { d:5, c:"Math", q:"A number is perfect if it equals the sum of its proper divisors. Which is perfect?", a:["12","18","28","32"], i:2 },
  { d:5, c:"Science", q:"Mitochondrial DNA in humans is inherited primarily from whom?", a:["The father","The mother","Both parents equally","Neither"], i:1 },
  { d:5, c:"World", q:"The paradox of the heap (sorites) challenges which idea?", a:["Precise borders of vague predicates","Conservation of energy","Supply and demand","Double-entry bookkeeping"], i:0 },
  { d:5, c:"History", q:"Queen Nzinga ruled the Mbundu kingdoms mainly in which present-day country?", a:["Angola","Mozambique","Senegal","Ethiopia"], i:0 },
  { d:5, c:"Science", q:"Superconductivity was first observed in mercury by Kamerlingh Onnes in about which year?", a:["1821","1911","1947","1986"], i:1 },
  { d:5, c:"Geography", q:"Which lake is the world's largest by surface area?", a:["Superior","Victoria","Caspian Sea","Baikal"], i:2 }
];
